services:
  tantian:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - STORAGE_SECRET=change-this-to-yor-own-private-secret
      - APP_HOST=0.0.0.0
      - APP_PORT=80