[project]
name = "tantian"
version = "0.1.1"
description = "A privacy-focused, real-time chat application built with NiceGUI."
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "apscheduler>=3.11.1",
    "nicegui>=3.3.1",
]
